# This file may be used to create an environment using:
#
# ## Miniconda or Anaconda
#     $ conda env create --file environment_arm64.yml --subdir=osx-64
# If you are using the zsh shell, run:
#     $ conda init zsh
# Or, if you are using a different shell, run:
#     $ conda init
# After init, if you do not want conda to change your global shell when
# you open a new terminal, run:
#     $ conda config --set auto_activate_base false
# Finally, activate the environment with:
#     $ conda activate tbp.monty
#     $ conda config --env --set subdir osx-64
#
# platform: osx-arm64
name: tbp.monty
channels:
  - aihabitat
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.8

  - aihabitat::habitat-sim=0.2.2
  - aihabitat::withbullet
  - conda-forge::cmake>=3.14.0
  - conda-forge::importlib_resources
  - conda-forge::matplotlib>=3.7.3
  - conda-forge::mkl<2022 # prevents Intel errors when osx-64 environment is running on osx-arm64 platform
  - conda-forge::numpy<=1.23.5 # numpy >=1.24.0 missing np.long
  - conda-forge::pandas
  - conda-forge::pillow
  - conda-forge::quaternion=2023.0.3 # later versions missing np.long
  - conda-forge::scikit-image
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::scipy>=1.10.1
  - conda-forge::sympy
  - conda-forge::tqdm
  - conda-forge::wandb
  - conda-forge::wget
  - pyg::pyg=2.1.0
  - pyg::pytorch-scatter=2.0.9
  - pyg::pytorch-sparse=0.6.15
  - pytorch::pytorch=1.13.1

  - pip
  - pip:
      - -e .[dev]
